### PR TITLE
Update index.css

### PR DESCRIPTION
**Pull request by hs-07**
Resolved the issues regarding blog section

### CODE REVIEW

**Comment by LBlend** [comment]
The relevant CSS is located [here](https://github.com/UiO-Gaming/uiogaming.no/blob/f4405b3ff89fbe013b4998a14715a1b45eb4f7b3/src/pages/blog.module.css#L16-L23). Not in the `index.css` file.

Besides, your solution presents some problems. Your solution works for the current blogposts and their respective images at the time of writing this however a new blogpost with a really short or tall image will cause issues. If the image is too short, there will be a gap between the image and the title box. If the image is too tall the blog card will be so tall to the point where it hurts the UX. Seeing only an image and having to scroll down to see the post title is not a good experience IMO.

Because of these reasons, I unfortunately can't merge the PR for the moment.

**Comment by hs-07** [comment]
@LBlend ok okk
I will work over these points and will make another and improved PR.
Thanks for the review.

**Comment by hs-07** [comment]
Actually i am facing an issue, whenever I am making changes in blog.module.css, no changes are reflecting on the app, and making changes in index.css, changes are visible in blog section.
I am a bit confused. @LBlend

**Comment by LBlend** [comment]
Are you running the application with `yarn start`?

**Comment by hs-07** [comment]
yes @LBlend

**Comment by LBlend** [comment]
hmm then I don't know. Sorry :(

**Pull request closed without merging**
